server:
  port: 9000
logging:
  level:
    sql: info
    org:
      springframework:
        security: INFO
  config: classpath:log4j2-spring.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/su?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/su?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
      username: "root"
      password: "000000"
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 30
  h2:
    console:
      enabled: true
  application:
    name: suhan
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ##  自动创建 JPA 数据库
      ddl-auto: none
  output:
    ansi:
      ## 日志颜色
      enabled: always
  sql:
    init:
      data-locations: classpath*:data.sql
      schema-locations: classpath*:schema.sql
      platform: mysql
      mode: never